### ISSUE TITLE
sort parameters should have sort attribute to document valid options

### ISSUE THREAD

**Issue by mbryzek** [flowcommerce/api-lint#45]
modify the linter to ensure there is a sort attribute for every operation that have a sort parameter

          "attributes": [
            {
              "name": "sort",
              "value": {
                "values": [
                  { "value": "id" },
                  { "value": "name", "default": true },
                  { "value": "categories" },
                  { "value": "experience" }
                ]
              }
            }
          ],

**Comment by ctumolosus** [comment]
I will look into this.
